version: "2"
services:
  java:
    build: ./java
    ports:
    - "6001:8080"
    image: krixerx/docker-java
  nodejs:
    build: ./nodejs
    ports:
    - "6002:8080"
    image: krixerx/docker-nodejs
  php:
    build: ./php
    ports:
    - "6003:80"
    image: krixerx/docker-php
  python:
    build: ./python
    ports:
    - "6004:8080"
    image: krixerx/docker-python